// skillsData.js
const skills = [
  { name: "HTML", icon: "html5" },
  { name: "CSS", icon: "css" },
  { name: "Tailwind CSS", icon: "tailwindcss" },
  { name: "SASS", icon: "sass" },
  // { name: 'Bootstrap', icon: 'bootstrap' },
  { name: "JavaScript", icon: "javascript" },
  // { name: 'TypeScript', icon: 'typescript' },
  { name: "React.js", icon: "react" },
  // { name: 'Next.js', icon: 'nextdotjs' },
  { name: "Framer Motion", icon: "framer" },
  { name: "Pug", icon: "pug" },
  { name: "Node.js", icon: "nodedotjs" },
  { name: "Express.js", icon: "express" },
  { name: "MongoDB", icon: "mongodb" },
  { name: "Mongoose", icon: "mongoose" },
  { name: "PostgreSQL", icon: "postgresql" },
  { name: "MySQL", icon: "mysql" },
  { name: "Firebase", icon: "firebase" },
  { name: "NGINX", icon: "nginx" },
  { name: "Redis", icon: "redis" },
  { name: "GraphQL", icon: "graphql" },
  { name: "Docker", icon: "docker" },
  { name: "Socket.io", icon: "socketdotio" },
  { name: "JWT", icon: "jsonwebtokens" },
  { name: 'pm2', icon: 'pm2' },
  { name: "Git", icon: "git" },
  { name: "GitHub", icon: "github" },
  { name: "Vercel", icon: "vercel" },
  { name: "OpenAI", icon: "openai" },
  { name: "Co-Pilot", icon: "githubcopilot" },
  { name: "Axios", icon: "axios" },
  { name: "StreamLit", icon: "streamlit" },
  { name: "Postman", icon: "postman" },
  { name: "RazorPay", icon: "razorpay" },

  // { name: 'Figma', icon: 'figma' },
  { name: "npm", icon: "npm" },
  { name: "C++", icon: "cplusplus" },
  { name: "SQLite", icon: "sqlite" },
];

export default skills;
